version: "3.9"

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: sh -c "npm ci && npm run build && npm run start:prod"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zeeks
      POSTGRES_PASSWORD: zeee
      POSTGRES_DB: mynestdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
